# Colors
background = "#0D0F14ff"
color = "#f3f4f5ff"
separator = "#5294e2ff"
tag_fg = "#f3f4f5ff"
tag_bg = "#30343Dff"
tag_focused_fg = "#f3f4f5ff"
tag_focused_bg = "#5294e2ff"
tag_urgent_fg = "#30343Dff"
tag_urgent_bg = "#cc241dff"
tag_inactive_fg = "#5294e2ff"
tag_inactive_bg = "#282828ff"

font = "FiraCode Nerd Font 10"
height = 18
command = "i3status-rs ~/.config/i3status/i3status-top.toml"
