---
name: dock
position: bottom
anchor_to_edges: false
height: 16
icon_theme: Yaru-blue-dark
margin:
  top: 0
  bottom: 4
center:
  - type: launcher
    favorites: [neovide, com.mitchellh.ghostty, brave-browser, discord, org.gnome.Nautilus]
    show_name: false
    show_icons: true
    icon_size: 38
